"""Agent module."""

from pydantic_ai import Agent
from dotenv import load_dotenv
from a2a.types import AgentSkill

from src.mcp_servers import todoist_server
from src.agents.common.agent import load_agent_config

load_dotenv(override=True)

todoist_agent_config = load_agent_config("src/agents/todoist_agent/config.yml")


class TodoistAgentCard:
    """
    Todoist Agent Card.
    """

    name: str = todoist_agent_config.name
    description: str = todoist_agent_config.description
    skills: list[AgentSkill] = []
    organization: str = todoist_agent_config.name
    port: int = todoist_agent_config.port
    host: str = todoist_agent_config.host


todoist_agent = Agent(
    model=todoist_agent_config.model,
    mcp_servers=[todoist_server],
    name=todoist_agent_config.name,
    system_prompt=todoist_agent_config.system_prompt,
)


async def run_todoist_agent(task: str) -> str:
    """
    Executes a Todoist-related natural language task asynchronously using the Todoist agent and returns the agent's response.

    Parameters:
        task (str): A natural language description of the Todoist task to process.

    Returns:
        str: The output generated by the Todoist agent after processing the task.
    """
    async with todoist_agent.run_mcp_servers():
        result = await todoist_agent.run(
            task,
        )
        return result.output


app = todoist_agent.to_a2a()
