"""Agent module."""

from datetime import datetime

from dotenv import load_dotenv
from pydantic_ai import Agent
from a2a.types import AgentSkill

from src.mcp_servers.gmail import server as gmail_server
from src.agents.common.agent import load_agent_config
from src.core.logger import logger

load_dotenv(override=True)

# Load configuration
gmail_agent_config = load_agent_config("src/agents/gmail_agent/config.yml")

# Calculate current date for logging
current_date = datetime.now().strftime("%Y-%m-%d")
logger.info("Gmail Agent: Using current date: %s", current_date)

# Format the system prompt and log it
formatted_system_prompt = gmail_agent_config.system_prompt.format(
    current_date=current_date
)
logger.info(
    "Gmail Agent: System prompt after date substitution (first 500 chars): %s...",
    formatted_system_prompt[:500],
)


class GmailAgentCard:
    """
    Gmail Agent Card.
    """

    name: str = gmail_agent_config.name
    description: str = gmail_agent_config.description
    skills: list[AgentSkill] = []
    organization: str = gmail_agent_config.name
    port: int = gmail_agent_config.port
    host: str = gmail_agent_config.host


# Only add MCP server if it's available
mcp_servers = [gmail_server] if gmail_server else []

gmail_agent = Agent(
    model=gmail_agent_config.model,
    mcp_servers=mcp_servers,
    name=gmail_agent_config.name,
    system_prompt=formatted_system_prompt,
)


async def run_gmail_agent(task: str) -> str:
    """
    Runs the Gmail AI agent asynchronously with the given task and returns the agent's response.

    Parameters:
        task (str): The instruction or query for the Gmail agent.

    Returns:
        str: The response generated by the Gmail agent.
    """
    # Log the task and current date for debugging
    runtime_date = datetime.now().strftime("%Y-%m-%d")
    logger.info(
        "Gmail Agent: Processing task: '%s' with runtime date: %s",
        task,
        runtime_date,
    )

    if mcp_servers:
        async with gmail_agent.run_mcp_servers():
            result = await gmail_agent.run(
                task,
            )
            return result.output
    else:
        # Run without MCP servers if not available
        result = await gmail_agent.run(
            task,
        )
        return result.output


app = gmail_agent.to_a2a()
