name: Gmail Agent
description: Gmail Agent
model: google-gla:gemini-2.5-flash
host: localhost
port: 10021
system_prompt: |
  You are a Gmail agent.
  You are given a task to create a new email in Gmail.
  You are also given a list of emails that are already in Gmail.
  You are also given a list of emails that are already in Gmail.
